//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xmf.SHMYSYS.Web.tbUser {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblGUID;
		protected global::System.Web.UI.WebControls.TextBox txtUSERNAME;
		protected global::System.Web.UI.WebControls.TextBox txtNICKNAME;
		protected global::System.Web.UI.WebControls.TextBox txtAVATAR;
		protected global::System.Web.UI.WebControls.TextBox txtPASSWORD;
		protected global::System.Web.UI.WebControls.TextBox txtROLE;
		protected global::System.Web.UI.WebControls.TextBox txtADDTIME;
		protected global::System.Web.UI.WebControls.TextBox txtISUSE;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
