//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xmf.SHMYSYS.Web.tbUser {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblGUID;
	protected global::System.Web.UI.WebControls.Label lblUSERNAME;
	protected global::System.Web.UI.WebControls.Label lblNICKNAME;
	protected global::System.Web.UI.WebControls.Label lblAVATAR;
	protected global::System.Web.UI.WebControls.Label lblPASSWORD;
	protected global::System.Web.UI.WebControls.Label lblROLE;
	protected global::System.Web.UI.WebControls.Label lblADDTIME;
	protected global::System.Web.UI.WebControls.Label lblISUSE;


       
    }
}
