//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xmf.SHMYSYS.Web.tbApply {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtGUID;
		protected global::System.Web.UI.WebControls.TextBox txtGIFTGUID;
		protected global::System.Web.UI.WebControls.TextBox txtAPPLYNUM;
		protected global::System.Web.UI.WebControls.TextBox txtAPPLYNAME;
		protected global::System.Web.UI.WebControls.TextBox txtAPPLYSTATE;
		protected global::System.Web.UI.WebControls.TextBox txtAPPLYDATE;
		protected global::System.Web.UI.WebControls.TextBox txtAUDITDATE;
		protected global::System.Web.UI.WebControls.TextBox txtRELEASEDATE;
		protected global::System.Web.UI.WebControls.TextBox txtISUSE;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
