//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xmf.SHMYSYS.Web.tbApply {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblGUID;
	protected global::System.Web.UI.WebControls.Label lblGIFTGUID;
	protected global::System.Web.UI.WebControls.Label lblAPPLYNUM;
	protected global::System.Web.UI.WebControls.Label lblAPPLYNAME;
	protected global::System.Web.UI.WebControls.Label lblAPPLYSTATE;
	protected global::System.Web.UI.WebControls.Label lblAPPLYDATE;
	protected global::System.Web.UI.WebControls.Label lblAUDITDATE;
	protected global::System.Web.UI.WebControls.Label lblRELEASEDATE;
	protected global::System.Web.UI.WebControls.Label lblISUSE;


       
    }
}
